### ISSUE TITLE
suspicious ImageShow dependency

### ISSUE THREAD

**Issue by johnnychen94** [tlnagy/OMETIFF.jl#83]
Does this package really need `ImageShow`? I ask this because OMETIFF sounds like a pure image IO backend.

**Comment by tlnagy** [comment]
I believe I originally included it for pragmatic reasons because sometimes the display would attempt to dump an enormous image after loading and crash IJulia. I believe this usually happened when it used `Colors.jl`'s show function instead of writing to a PNG and reading it back in like `ImageShow`. Not sure if that's been fixed.

**Comment by tlnagy** [comment]
Given that I don't see any ill effects of not having ImageShow in TiffImages, I went ahead and merged.

**Comment by johnnychen94** [comment]
That issue was fixed in https://github.com/JuliaGraphics/Colors.jl/pull/346
